### ISSUE TITLE
<summary> is not recognized.

### ISSUE THREAD

**Issue by Levent0z** [mdx-js/mdx#2263]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Latest in your plaground

### Steps to reproduce

Go to the MDX playground and put in:

```
# Test

<details>
    <summary>This should be the title of the section but it's not</summary>
    Lorem Ipsum
</details>
```

### Expected behavior

The text inside the summary should be the text of the expander.

### Actual behavior

The text of the expander says "Details"

### OS

macOS

**Comment by ChristianMurphy** [comment]
Welcome @Levent0z! 👋 
The behavior is expected.
There are some rather fine grained rules around what is considered block vs inline content in JSX.
See some recent conversations around this for more context https://github.com/orgs/mdx-js/discussions/2194, https://github.com/mdx-js/mdx/issues/2181, https://github.com/mdx-js/mdx/issues/2172, https://github.com/mdx-js/mdx/issues/2053, https://github.com/mdx-js/mdx/issues/2243


The issue you are running into is the same, inline vs block conflict, with a block which generates an inner paragraph.
Because there is a newline after `<details>` the nextline becomes a markdown block, that block by default will have a paragraph.
Which is translated to:

```html
<details>
  <p>
    <summary>This is how MDX works</summary>
    Lorem Ipsum
  </p>
</details>
```

`<summary>` must be a direct child of `<details>` to appear.

There are a couple ways to resolve this.

## Make the content a JSX expression

so that no markdown paragraph appears, using a wrapping `{}`

```jsx
{<details>
    <summary>This is how MDX works</summary>
    Lorem Ipsum
</details>}
```

## Make the content a JSX inline so no paragraph appears


```jsx
<details><summary>This is how MDX works</summary>Lorem Ipsum</details>
```

**Comment by tats-u** [comment]
@ChristianMurphy It works if an empty line is added after the `<summary>` element, right?

```mdx
<details>
    <summary>This is how MDX works</summary>

    Lorem Ipsum
</details>
```

↓hast to YAML

```yaml
type: root
children:
- type: mdxJsxFlowElement
  name: details
  attributes: []
  data:
    _mdxExplicitJsx: true
  children:
  - type: mdxJsxFlowElement
    name: summary
    attributes: []
    data:
      _mdxExplicitJsx: true
    children:
    - type: text
      value: This is how MDX works
  - type: element
    tagName: p
    properties: {}
    children:
    - type: text
      value: Lorem Ipsum
```
