### ISSUE TITLE
Acorn parsing error in frontmatter

### ISSUE THREAD

**Issue by davidthor** [mdx-js/mdx#2354]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v2.3.0

### Link to runnable example

https://codesandbox.io/p/sandbox/quizzical-parm-8vnd52?file=/index.js

### Steps to reproduce

I'm trying to use frontmatter to pass data from pages to a layout component, but am running into issues with the frontmatter contents. It seems like acorn is trying to parse the string frontmatter contents and it isn't liking some of the contents of my strings.

In my case, I'm trying to pass data for code blocks to put in a hero component. My frontmatter looks something like this:

```yml
---
title: My page title
hero:
  codeBlocks:
    - label: filename.hcl
      language: hcl
      code: |
        variable "region" {
          type = "string"
          description = "Region to put stuff in"
        }
---
```

With the above, I'm getting the error:

> Could not parse expression with acorn: Unexpected content after expression

See the codesandbox link for more details

### Expected behavior

I expected the frontmatter to be interpretted as a string and not error

### Actual behavior

I get the error "Could not parse expression with acorn: Unexpected content after expression"

### Runtime

Node v18

### Package manager

npm v9

### OS

macOS

### Build and bundle tools

Gatsby
